import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import axios, { AxiosError } from 'axios'
import { useRouter } from 'next/router';
import { useState } from 'react';

axios.defaults.baseURL = 'http://localhost:8081';

export default function Home() {
  const router = useRouter();
  const [username, setUsername] = useState('');
  const [password, setPassword] = useState('');

  const handleLogin = async () => {
    // TODO: 处理登录逻辑
    console.log("username: ", username);
    console.log("password: ", password);

    try {
      // 调用登录接口
      const response = await axios.post('/user/login', {
        username,
        password
      });
  
      console.log(response);
      // 登录成功提示
      alert(response.data);
      // 跳转到detail页面
      router.push('/detail');
    } catch (error: any) {
      const e: AxiosError = error;
      console.log(e?.code);
      console.log(e);
      // 登录失败提示
      alert(e?.response?.data);
    }
  };

  const handleRegister = async () => {
    try {
      // 调用注册接口
      const response = await axios.post('/user/register', {
        username,
        password
      });
  
      console.log(response);
      // 注册成功提示
      alert(response.data);
    } catch (error: any) {
      const e: AxiosError = error;
      console.log(e?.code);
      console.log(e);
      // 注册失败提示
      alert(e?.response?.data);
    }
  };
  

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <p className={styles.description}>
          Please login to continue:
        </p>

        <form className={styles.form}>
          <div className={styles.formItem}>
            <label htmlFor="username" className={styles.label}>Username:</label>
            <input type="text" id="username" name="username" className={styles.input} required value={username} onChange={(e) => setUsername(e.target.value)} />
          </div>
          <div className={styles.formItem}>
            <label htmlFor="password" className={styles.label}>Password:</label>
            <input type="password" id="password" name="password" className={styles.input} required value={password} onChange={(e) => setPassword(e.target.value)} />
          </div>
          <div className={styles.buttonGroup}>
            <button type="button" className={styles.loginButton} disabled={!username || !password} onClick={handleLogin}>登录</button>
            <button type="button" className={styles.registerButton} disabled={!username || !password} onClick={handleRegister}>注册</button>
          </div>
        </form>

        {/* <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div> */}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
